import Link from 'next/link';

export function AnalyticsComboCards() {
  return <>
    <div className="combo-section-banner"><div className="combo-section-title-wrap"><h2 className="combo-section-title">Peer Alignment Breakdown</h2></div><Link href="/participants" className="combo-section-action-link" title="Explore individual participant perspectives"><span>View Participants</span><span aria-hidden="true">›</span></Link></div>
    <div className="analytics-grid-row-2">
      <article className="analytics-card-base card-two-sided"><div className="analytics-card-header"><div className="card-title-group"><span className="card-title-sparkle">✦</span><span className="card-title-text">Strongest Agreement</span></div><span className="card-badge-pill tone-positive">96% Match</span></div><div className="dual-side-comparison"><div className="party-statement-box"><div className="party-header"><span className="party-avatar-mini avatar-color-indigo">A</span><span className="party-label">You</span></div><p className="party-quote">“The project should launch this month as an MVP.”</p></div><div className="party-vs-spine"><span className="party-vs-badge tone-positive">96%</span></div><div className="party-statement-box"><div className="party-header"><span className="party-avatar-mini avatar-color-cyan">AL</span><span className="party-label">Alex</span></div><p className="party-quote">“Targeting final week of this month for initial release.”</p></div></div></article>
      <article className="analytics-card-base card-two-sided"><div className="analytics-card-header"><div className="card-title-group"><span className="card-title-sparkle">✦</span><span className="card-title-text">Biggest Disagreement</span></div><span className="card-badge-pill tone-negative">31% Match</span></div><div className="dual-side-comparison"><div className="party-statement-box"><div className="party-header"><span className="party-avatar-mini avatar-color-indigo">A</span><span className="party-label">You</span></div><p className="party-quote">“Product Lead should own final design sign-off for market fit.”</p></div><div className="party-vs-spine"><span className="party-vs-badge tone-divergent">VS</span></div><div className="party-statement-box"><div className="party-header"><span className="party-avatar-mini avatar-color-cyan">AL</span><span className="party-label">Alex</span></div><p className="party-quote">“Design Lead must retain full creative autonomy over UX flow.”</p></div></div></article>
    </div>
    <div className="analytics-grid-row-3">
      <article className="analytics-card-base"><div className="analytics-card-header"><div className="card-title-group"><span className="card-title-sparkle">✦</span><span className="card-title-text">Shared Assumptions</span></div><span className="card-badge-pill tone-indigo">Unstated Consensus</span></div><div className="insight-contrast-card"><span className="insight-contrast-header">You Both Assumed</span><p className="insight-contrast-body">“The first release is strictly an MVP.” Neither of you factored in enterprise multi-tenancy or invoice automation for v1.</p></div></article>
      <article className="analytics-card-base"><div className="analytics-card-header"><div className="card-title-group"><span className="card-title-sparkle">✦</span><span className="card-title-text">Hidden Mismatch</span></div><span className="card-badge-pill tone-amber">Nuance Divergence</span></div><div className="insight-contrast-card" style={{ background: '#FFFBEB', borderColor: '#FDE68A', borderLeftColor: '#F59E0B' }}><span className="insight-contrast-header" style={{ color: '#B45309' }}>Conflicting Definitions</span><p className="insight-contrast-body" style={{ color: '#78350F' }}>Both answered{' '}<strong>“Yes”</strong>{' '}to launching this month — but you meant{' '}<em>public general availability</em>, while Alex meant{' '}<em>closed private beta</em>.</p></div></article>
      <article className="analytics-card-base"><div className="analytics-card-header"><div className="card-title-group"><span className="card-title-sparkle">✦</span><span className="card-title-text">Near Agreement</span></div><span className="card-badge-pill tone-positive">Easy to Resolve</span></div><div className="insight-contrast-card" style={{ background: '#F0FDF4', borderColor: '#BBF7D0', borderLeftColor: '#10B981' }}><span className="insight-contrast-header" style={{ color: '#047857' }}>Sprint Duration</span><p className="insight-contrast-body" style={{ color: '#064E3B' }}>You proposed{' '}<strong>2 weeks</strong>, Alex proposed{' '}<strong>3 weeks</strong>. A 5-minute alignment sync can easily establish compromise on a 2.5-week cadence.</p></div></article>
    </div>
  </>;
}
